providers = []

[phases.setup]
nixPkgs = ["...", "python3", "gcc", "gnumake"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd client && npm run build",
  "cd client/server && npm run build"
]

[start]
cmd = "cd client/server && node dist/index.js"
